0'TEENY - TANDY Model 200 North America - github.com/bkw777/dl2 - loader: co2ba.sh b.kenyon.w@gmail.com 2026-10-10
0READF:CLEAR12,F:DEFINTA-E,Q,G,K:DEFSNGF,H-J:DEFSTRL-O:READF,A,J,G,N,E,Q:M="!":C=0:I=F:H=F+A-1:K=0:D=0:CLS:?USING"Installing \    \   0%";N
1READL:FORC=1TOLEN(L):O=MID$(L,C,1):IFO=MTHEND=E:NEXT:ELSEB=ASC(O)XORD:B=BXORQ:D=0:POKEI,B:I=I+1:K=KXORB:NEXT:?@18,USING"###%";(I-F)*100/A:IFI<=HTHEN1
2IFK<>GTHEN?"Bad Checksum":ELSEM=CHR$(34):L="X.DO":OPENLFOROUTPUTAS1:?#1,"0CLEAR0,"F":CALL"J":MENU":CLOSE1:?"Please type:":?"KILL"M""L:?"SAVE"M""N:LOADL
3DATA60461,643,60461,80,"TEENY",128,64
4DATA"a@@yb¶·a!š!šbº·j¶·¹ïr¸·az¬¥aÏ®ŒQr^½¶!”aÁ¬bt¯a1¯vbŽ!š!¢lz0¯¾!‘Šä'¾!“ŠW®µò¬ŠÁ¬±–!‹Šu­}Š!‡­z¸·÷ŠÓ¬j²·!„!j°·šÂaê®ŒQƒz¬[:ó‚Ü¬‰yx!Žq!„!Ž!Ža¼·7cv@‰õÇVnÜ¬aã¬w]Y~G!›®ïê¬vZcQ2¯FIú!FOv`cE‚—¬v!†c0a¼·>cÆ!—>!Ÿ!‡c÷:Š¸¬Æc]‚²¬o7~EÀ!‡aº·>!ƒÆšÁ¬cE‚A­a¼
5DATA"·àÏl­l­!Ll­M‚[­ïpa½·!Žc>÷‰YÅ‚Á¬7c‰~Eƒ!›®^A~Aê¬7c3ƒ!ž®Œk‚Á¬aÁ¬bt¯Al¥N®jW¸!…!Œ) b´·K!Ÿ|C}‚'­!—a›­YYYYY>µQD®•c!žc!–•c!žc&+!žc!– )b²·«b°·¥èÂšÁ¬a¸·tƒ­j´·«¡z¼·!F@:ó9r¼·ˆ÷¼ˆ­[¥a¾·I>¡7cLƒê­^C|­¥•~Cê¬¢¬ï!‡!r¼·‘¡‰à½­#¶€ª­!¡¶À­­Õ²vZ‰ï7c7j²·«j
6DATA"!¡¶Yb!¡¶‰j°·b#¶‰±j°·«[¡ƒìmz!Œ·–!ƒ°~B‰ò¬‚Á¬z!Œ·¾!‚šÁ¬¾!…’Á¬ŒkŠÁ¬N®!~BÑ…•«l‘=Ó/<Ú'LckM‚!‡®=ôˆ•¥z­‘¡!¢®~Bê¬¢¬ˆ¥¥aÀ@Ÿ’>®!!„¡I£«AÀ¿I¥Á®‘¡ƒ!¢®!‹¡‘~Dê¬1c!ú!ƒ!ž®~`!ƒ`!†!†!†!†!†!†n!˜!˜`h!ƒ}!‹!Œ!“!‘iMJ~`@!…!’!’MJ@
