0'TEENY - Kyotronic KC-85 North America - github.com/bkw777/dl2 - loader: co2ba.sh b.kenyon.w@gmail.com 2026-10-10
0READF:CLEAR12,F:DEFINTA-E,Q,G,K:DEFSNGF,H-J:DEFSTRL-O:READF,A,J,G,N,E,Q:M="!":C=0:I=F:H=F+A-1:K=0:D=0:CLS:?USING"Installing \    \   0%";N
1READL:FORC=1TOLEN(L):O=MID$(L,C,1):IFO=MTHEND=E:NEXT:ELSEB=ASC(O)XORD:B=BXORQ:D=0:POKEI,B:I=I+1:K=KXORB:NEXT:?@18,USING"###%";(I-F)*100/A:IFI<=HTHEN1
2IFK<>GTHEN?"Bad Checksum":ELSEM=CHR$(34):L="X.DO":OPENLFOROUTPUTAS1:?#1,"0CLEAR0,"F":CALL"J":MENU":CLOSE1:?"Please type:":?"KILL"M""L:?"SAVE"M""N:LOADL
3DATA62323,637,62323,195,"TEENY",128,64
4DATA"a@@ybF½a!š!šbJ½jF½¹ïrH½aÀ³¥aµéQr+¿¸!…a‡³b!™¶aÍ¶vb…!‹YazÌ¶¾!‘Šä!”¾!“Š!•µµ¶³Š‡³±–!‹Š9´}ŠË´zH½÷Š™³jB½!„!j@½ç(a«µéQƒÀ³[:ó‚¢³‰yx!Žq!„aL½7cv@‰¤+Vn¢³a©³wˆW~GÙµï®³vZcQÎ¶FI!‚tFOv`cE‚[´v!†c0aL½>cÆ!—>!Ÿ!‡c÷:Š|´Æc]‚v´o7~EÀ!‡aJ½>z+š‡³cE‚!…´aL½J3
5DATA"0´0´!L0´M‚!Ÿ´ïpaM½!Žc>÷‰Æ*‚‡³7c‰~EƒÙµ^A~A®³7c3ƒÜµÀ`‚‡³õ`¥!Œµjg½!…!Œ) bD½K!Ÿ|C}‚å´!—aYµYYYYY>µQ!‚µ•c!žc!–•c!žc&+!žc!– )bB½«b@½¥5(š‡³aH½tAµjD½«¡zL½!F@:ó9rL½ˆ÷¼Fµ[¥aN½I>¡7cLƒ¨´^CÀ´¥•~C®³f´ï!‡!rL½‘¡‰à{µ‚»€hµ€»ÀkµË¹vZ‰ï7c7jB½«j€»Yb€»‰j@½b
6DATA"‚»‰±j@½«[¡ƒQbzë¼–!ƒ°~B‰¶³‚‡³zë¼¾!‚š‡³¾!…’‡³À`Š‡³!Œµ!~BÑ…•«5a‘=Ó/<Ú'LckM‚Åµ=ôˆ•¥>´‘¡ãµ~B®³f´ˆƒ‡³¥¥aÀ@Ÿ’ÿµ!!„¡I£«AÀ¿I¥‚µ‘¡ƒãµ!‹¡‘~D®³1c!!‚tƒÜµ~`!ƒ`!†!†!†!†!†!†n!˜!˜`h!ƒ}!‹!Œ!“!‘iMJ~`@!…!’MJ@
